name: Multi-Repo Homeostat

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

env:
  HOMEOSTAT_ENV: production
  LEARNING_ENABLED: true
  APPLY_MODE: propose
  CONFIDENCE_THRESHOLD: 0.8
  MAX_DIFF_LINES: 500
  MAX_FILES: 10
  MAX_RUN_COST: 1.0

jobs:
  orchestrate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: [convert-my-file, notebridge, palette-kit]
      max-parallel: 1

    steps:
      - name: Checkout Homeostat
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Load Repo Config
        id: config
        run: |
          CONFIG=$(yq e '.repositories[] | select(.slug == "littlebearapps/${{ matrix.repo }}")' .homeostat/repos.yml -o json)
          echo "config=$CONFIG" >> $GITHUB_OUTPUT

      - name: Clone Target Repo
        run: |
          git clone --depth=1 \
            https://x-access-token:${{ secrets.HOMEOSTAT_PAT }}@github.com/littlebearapps/${{ matrix.repo }}.git \
            target-repo

      - name: Run Homeostat
        id: homeostat
        run: |
          node homeostat/multi-repo/orchestrator.js \
            --repo ${{ matrix.repo }} \
            --config '${{ steps.config.outputs.config }}'
        env:
          DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.HOMEOSTAT_PAT }}

      - name: Generate Summary
        if: always()
        run: |
          cat > $GITHUB_STEP_SUMMARY << EOF
          ## Homeostat Run: ${{ matrix.repo }}

          **Repository**: littlebearapps/${{ matrix.repo }}
          **Issues Processed**: ${{ steps.homeostat.outputs.processed }}
          **PRs Created**: ${{ steps.homeostat.outputs.created }}
          **PRs Updated**: ${{ steps.homeostat.outputs.updated }}
          **Fingerprints Cooled Down**: ${{ steps.homeostat.outputs.cooldown }}
          **Cost**: \${{ steps.homeostat.outputs.cost }}
          **Tokens**: ${{ steps.homeostat.outputs.tokens }}
          EOF
